name: Build kernel image

on:
  workflow_dispatch:
    # Enable manual trigger of this action.
    inputs:
      kernel1:
        description: Kernel 1 version.
        default: 4.14.182
        required: true
      kernel2:
        description: Kernel 2 version.
        default: 4.19.125
        required: true
      kernel3:
        description: Kernel 3 version.
        default: 5.4.43
        required: true

env:
  REGISTRY: ghcr.io/darkowlzz

jobs:
  kernel1:
    runs-on: ubuntu-latest
    env:
      KERNEL_VERSIONS: ${{ github.event.inputs.kernel1 }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_HOST }}
          password: ${{ secrets.CR_PAT }}
      - name: Build kernel for amd64
        env:
          GOARCH: amd64
        working-directory: images/kernel
        run: make
      - name: Build kernel for arm64
        env:
          GOARCH: arm64
        working-directory: images/kernel
        run: make
      - name: Push images
        working-directory: images/kernel
        run: make push

  kernel2:
    runs-on: ubuntu-latest
    env:
      KERNEL_VERSIONS: ${{ github.event.inputs.kernel2 }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_HOST }}
          password: ${{ secrets.CR_PAT }}
      - name: Build kernel for amd64
        env:
          GOARCH: amd64
        working-directory: images/kernel
        run: make
      - name: Build kernel for arm64
        env:
          GOARCH: arm64
        working-directory: images/kernel
        run: make
      - name: Push images
        working-directory: images/kernel
        run: make push

  kernel3:
    runs-on: ubuntu-latest
    env:
      KERNEL_VERSIONS: ${{ github.event.inputs.kernel3 }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_HOST }}
          password: ${{ secrets.CR_PAT }}
      - name: Build kernel for amd64
        env:
          GOARCH: amd64
        working-directory: images/kernel
        run: make
      - name: Build kernel for arm64
        env:
          GOARCH: arm64
        working-directory: images/kernel
        run: make
      - name: Push images
        working-directory: images/kernel
        run: make push
