name: Build kernel image

on:
  workflow_dispatch:
    # Enable manual trigger of this action.

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build kernel
        run: |
          cd images/kernel
          make
