name: Build OS Image

on:
  workflow_dispatch:
    # Enable manual trigger of this action.
    inputs:
      arch:
        description: Platform architecture (amd64, arm64).
        default: amd64
        required: true
      what:
        description: WHAT OS image build argument (one of amazon-kernel, amazonlinux, alpine, opensuse, ubuntu, centos, kubeadm)
        required: true
      release:
        description: RELEASE OS image build argument (latest or specific version of OS)
        default: latest
        required: true
      user:
        description: Container registry user.
        default: weaveworks
        required: true

env:
  GOARCH: ${{ github.event.inputs.arch }}
  # Final image name: weaveworks/ignite-ubuntu:latest
  IMAGE_NAME: ${{ github.event.inputs.user }}/ignite-${{ github.event.inputs.what }}:${{ github.event.inputs.release }}

jobs:
  build-os-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image ${{ github.event.inputs.user }}/${{ github.event.inputs.what }}:${{ github.event.inputs.release }} for ${{ env.GOARCH }}
        run: |
          cd images
          make build WHAT=${{ github.event.inputs.what }} RELEASE=${{ github.event.inputs.release }} GOARCH=${{ env.GOARCH }} DOCKER_USER=${{ github.event.inputs.user }}
      - name: Log into Container Registry
        # NOTE: Create a PAT with `read:packages` and `write:packages` scopes
        # and save it as an Actions secret `CR_PAT`.
        # Create another Actions secret `CR_HOST` with the value as the
        # container registry host name, e.g.: docker.io, ghcr.io, gcr.io
        run: echo "${{ secrets.CR_PAT }}" | docker login "${{ secrets.CR_HOST }}" -u ${{ github.actor }} --password-stdin

      - name: Push image to Container Registry
        run: |
          IMAGE=${{ secrets.CR_HOST }}/${{ env.IMAGE_NAME }}
          # Change all uppercase to lowercase
          IMAGE=$(echo $IMAGE | tr '[A-Z]' '[a-z]')
          echo IMAGE=$IMAGE
          docker tag ${{ env.IMAGE_NAME }} $IMAGE
          docker push $IMAGE
